---
- name: ASA Deploy REST API.
  hosts: all
  connection: network_cli
  #connection: local
  gather_facts: no
  become_method: enable
  become: yes

  tasks:
  - name: ASA Deploy REST API
    cisco.asa.asa_config:
      commands:
       #- "show run"
       - "rest-api image disk0:/asa-restapi-7141-lfbff-k8.SPA"
       - "rest-api agent"
       - "http server enable"
       - "http 192.168.0.0 255.255.255.0 inside"
       #- "show run rest-api"

