---
- name: ASA Show Version.
  hosts: all
  connection: local
  gather_facts: no

  tasks:

          #  - name: "Show the ASA version"
          #    asa_command:
          #      commands:
          #        - show version
          #    become:  yes
          #    register: asacommands

  - name: "ASA Show, ver, ssh, telnet,rest, nat"
    asa_command:
      commands: 
       # - show version
        - show run ssh
        - show run telnet
        - show run http
        - show run rest-api
        - show asdm image
       # - show run nat
        - show run username
       # - show nat

    become: true
    register: asacommands

  - name: "Debug ASA Command Results"
    debug: msg="{{ asacommands}}"

